karnak: wifi: add quotes to fix the compilation error
[ 99% 6481/6535]
//frameworks/opt/net/wifi/libwifi_hal:libwifi-hal-common clang++
wifi_hal_common.cpp
FAILED:
out/soong/.intermediates/frameworks/opt/net/wifi/libwifi_hal/libwifi-hal-common/android_vendor.34_arm_armv7-a-neon_cortex-a7_static_cfi/obj/frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.o
PWD=/proc/self/cwd
prebuilts/clang/host/linux-x86/clang-r487747c/bin/clang++ -c
-D__ANDROID_VNDK__ -D__ANDROID_VENDOR__ -mthumb -Os -fomit-frame-pointer
-DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-s
elf -Wpointer-arith -Wunreachable-code-loop-increment
-no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar
-O3 -g -fdebug-default-version=5 -fno-strict-aliasing -Werror=date-time
-Werror=pragma
-pack -Werror=pragma-pack-suspicious-include -Werror=string-plus-int
-Werror=unreachable-code-loop-increment
-Wno-error=deprecated-declarations
-D__compiler_offsetof=__builtin_offsetof -faddrsig -fcommon -Werror
=int-conversion -Wno-reserved-id-macro -fcolor-diagnostics
-Wno-sign-compare -Wno-inconsistent-missing-override -Wno-c99-designator
-Wno-gnu-designator -Wno-gnu-folding-constant
-Wno-compound-token-split-by-macr
o -Wunguarded-availability -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__
-ffp-contract=off -fdebug-prefix-map=/proc/self/cwd=
-ftrivial-auto-var-init=zero
-enable-trivial-auto-var-init-zero-knowing-it-will-be-remov
ed-from-clang -Wno-unused-command-line-argument -ffunction-sections
-fdata-sections -fno-short-enums -funwind-tables
-fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2
-Wstrict-aliasing=2 -Werror=ret
urn-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point
-Werror=format-security -nostdlibinc -fdebug-info-for-profiling
-msoft-float -march=armv7-a -mfloat-abi=softfp -mfpu=neon
-mcpu=cortex-a7
-mfpu=neon-vfpv4 -D__ARM_FEATURE_LPAE=1 -target
armv7a-linux-androideabi34 -DANDROID_STRICT -fPIC -Wsign-promo
-Wimplicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS
-Wno-gnu-include-next -fvisibility
-inlines-hidden  -Iframeworks/opt/net/wifi/libwifi_hal/include
-Iframeworks/opt/net/wifi/libwifi_hal
-Isystem/core/libcutils/include_outside_system -Iexternal/libcxx/include
-Iexternal/libcxxabi/include -Isystem
/libbase/include -Iexternal/fmtlib/include -isystem
out/soong/.intermediates/bionic/libc/libc/android_vendor.34_arm_armv7-a-neon_cortex-a7_shared/gen/include
-isystem bionic/libc/kernel/uapi/asm-arm -isystem bio
nic/libc/kernel/uapi -isystem bionic/libc/kernel/android/scsi -isystem
bionic/libc/kernel/android/uapi -Wall -Werror -Wextra -Winit-self
-Wno-unused-function -Wno-unused-parameter -Wshadow -Wunused-variable
-Wwr
ite-strings -DWIFI_DRIVER_FW_PATH_STA=STA -DWIFI_DRIVER_FW_PATH_AP=AP
-DWIFI_DRIVER_FW_PATH_P2P=P2P
'-DWIFI_DRIVER_FW_PATH_PARAM="/dev/wmtWifi"'
-DWIFI_DRIVER_STATE_CTRL_PARAM=/dev/wmtWifi -DWIFI_DRIVER_STATE_ON
=1 -DWIFI_DRIVER_STATE_OFF=0 -flto -fsanitize-cfi-cross-dso
-fsanitize-ignorelist=external/compiler-rt/lib/cfi/cfi_blocklist.txt
-fvisibility=default -fsanitize=cfi -fsanitize-trap=all
-ftrap-function=abort -std
=gnu++17 -fno-rtti  -Werror=bool-operation
-Werror=format-insufficient-args -Werror=implicit-int-float-conversion
-Werror=int-in-bool-context -Werror=int-to-pointer-cast
-Werror=pointer-to-int-cast -Werror=xor-u
sed-as-pow -Wno-void-pointer-to-enum-cast -Wno-void-pointer-to-int-cast
-Wno-pointer-to-int-cast -Werror=fortify-source
-Werror=address-of-temporary -Werror=null-dereference
-Werror=return-type -Wno-tautological
-constant-compare -Wno-tautological-type-limit-compare
-Wno-reorder-init-list -Wno-implicit-int-float-conversion
-Wno-tautological-overlap-compare -Wno-deprecated-copy
-Wno-range-loop-construct -Wno-zero-as-null
-pointer-constant -Wno-deprecated-anon-enum-enum-conversion
-Wno-pessimizing-move -Wno-non-c-typedef-for-linkage -Wno-align-mismatch
-Wno-error=unused-but-set-variable -Wno-error=unused-but-set-parameter
-Wno-er
ror=deprecated-builtins -Wno-error=deprecated
-Wno-error=single-bit-bitfield-constant-conversion
-Wno-error=enum-constexpr-conversion -MD -MF
out/soong/.intermediates/frameworks/opt/net/wifi/libwifi_hal/libwifi-
hal-common/android_vendor.34_arm_armv7-a-neon_cortex-a7_static_cfi/obj/frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.o.d
-o
out/soong/.intermediates/frameworks/opt/net/wifi/libwifi_hal/libwifi-hal-common/a
ndroid_vendor.34_arm_armv7-a-neon_cortex-a7_static_cfi/obj/frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.o
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:109:16: error:
expected expression
    if (access(WIFI_DRIVER_STATE_CTRL_PARAM, W_OK) == 0)
               ^
<command line>:16:38: note: expanded from macro
'WIFI_DRIVER_STATE_CTRL_PARAM'
                                     ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:109:16: error:
use of undeclared identifier 'dev'; did you mean 'div'?
<command line>:16:39: note: expanded from macro
'WIFI_DRIVER_STATE_CTRL_PARAM'
                                      ^
external/libcxx/include/stdlib.h:118:42: note: 'div' declared here
inline _LIBCPP_INLINE_VISIBILITY lldiv_t div(long long __x, long long
__y) _NOEXCEPT {return lldiv(__x, __y);}
                                         ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:109:16: error:
use of undeclared identifier 'wmtWifi'
    if (access(WIFI_DRIVER_STATE_CTRL_PARAM, W_OK) == 0)
               ^
<command line>:16:43: note: expanded from macro
'WIFI_DRIVER_STATE_CTRL_PARAM'
                                          ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:118:32: error:
expected expression
  fd = TEMP_FAILURE_RETRY(open(WIFI_DRIVER_STATE_CTRL_PARAM, O_WRONLY));
                               ^
<command line>:16:38: note: expanded from macro
'WIFI_DRIVER_STATE_CTRL_PARAM'
                                     ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:118:32: error:
use of undeclared identifier 'dev'; did you mean 'div'?
<command line>:16:39: note: expanded from macro
'WIFI_DRIVER_STATE_CTRL_PARAM'
                                      ^
external/libcxx/include/stdlib.h:118:42: note: 'div' declared here
inline _LIBCPP_INLINE_VISIBILITY lldiv_t div(long long __x, long long
__y) _NOEXCEPT {return lldiv(__x, __y);}
                                         ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:118:32: error:
use of undeclared identifier 'wmtWifi'
  fd = TEMP_FAILURE_RETRY(open(WIFI_DRIVER_STATE_CTRL_PARAM, O_WRONLY));
                               ^
<command line>:16:43: note: expanded from macro
'WIFI_DRIVER_STATE_CTRL_PARAM'
                                          ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:118:32: error:
expected expression
<command line>:16:38: note: expanded from macro
'WIFI_DRIVER_STATE_CTRL_PARAM'
                                     ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:118:32: error:
use of undeclared identifier 'dev'; did you mean 'div'?
<command line>:16:39: note: expanded from macro
'WIFI_DRIVER_STATE_CTRL_PARAM'
                                      ^
external/libcxx/include/stdlib.h:118:42: note: 'div' declared here
inline _LIBCPP_INLINE_VISIBILITY lldiv_t div(long long __x, long long
__y) _NOEXCEPT {return lldiv(__x, __y);}
                                         ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:118:32: error:
use of undeclared identifier 'wmtWifi'
  fd = TEMP_FAILURE_RETRY(open(WIFI_DRIVER_STATE_CTRL_PARAM, O_WRONLY));
                               ^
<command line>:16:43: note: expanded from macro
'WIFI_DRIVER_STATE_CTRL_PARAM'
                                          ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:194:7: error: no
matching function for call to 'wifi_change_driver_state'
  if (wifi_change_driver_state(WIFI_DRIVER_STATE_ON) < 0) {
      ^~~~~~~~~~~~~~~~~~~~~~~~
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:98:5: note:
candidate function not viable: no known conversion from 'int' to 'const
char *' for 1st argument
int wifi_change_driver_state(const char *state) {
    ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:245:14: error:
use of undeclared identifier 'STA'
      return WIFI_DRIVER_FW_PATH_STA;
             ^
<command line>:12:33: note: expanded from macro
'WIFI_DRIVER_FW_PATH_STA'
                                ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:247:14: error:
use of undeclared identifier 'AP'
      return WIFI_DRIVER_FW_PATH_AP;
             ^
<command line>:13:32: note: expanded from macro 'WIFI_DRIVER_FW_PATH_AP'
                               ^
frameworks/opt/net/wifi/libwifi_hal/wifi_hal_common.cpp:249:14: error:
use of undeclared identifier 'P2P'
      return WIFI_DRIVER_FW_PATH_P2P;
             ^
<command line>:14:33: note: expanded from macro
'WIFI_DRIVER_FW_PATH_P2P'
                                ^
13 errors generated.

Change-Id: I9b31181611b37d45fa2ee15a2be1884676560708
Signed-off-by: Kai Jones <19639817+488315@users.noreply.github.com>