karnak: manifest: Remove android.hardware.cas entry
IMediaCasService is now converted to use vintf fragments
error: /manifest/android.hardware.cas@1.0-service.xml" cannot be added: HAL "android.hardware.cas" has a conflict.
https://android.googlesource.com/platform/hardware/interfaces/+/bf608fcc23a59bb7a3f02cc735fa5beee72c05e2%5E%21

Change-Id: I3312a0d3a28b863436a871a5e3eebc4d2d7d4fa0
Signed-off-by: Kai Jones <zaksenoj@icloud.com>